In [ ]:
#Given the following python code, what would the output of the code give?
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [3]:
import pandas as pd
url = '/content/sample_data/FoodBalanceSheets_E_Africa_NOFLAG.csv'
df= pd.read_csv(url, encoding= 'latin-1')
df.describe()
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:
df['Area'].count()

60943

In [4]:
#What is the total number and percentage of missing data in 2014 to 3 decimal places?
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [ ]:
#Which year had the least correlation with ‘Element Code’?
df.corr()

In [5]:
#Perform a groupby operation on ‘Element’.  What year has the highest sum of Stock Variation?
group_by_E_year = df.groupby(['Element'])[['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']].sum()
group_by_E_year.iloc[-3]

Y2014    58749.83
Y2015    34910.99
Y2016    33140.12
Y2017    54316.91
Y2018    20577.91
Name: Stock Variation, dtype: float64

In [6]:
#What is the total Protein supply quantity in Madagascar in 2015?
pro_supply_2015 = df.groupby(['Area']).get_group('Madagascar')
pro_supply_2015.groupby(['Element']).get_group('Protein supply quantity (g/capita/day)').sum()

Area Code                                                   14319
Area            MadagascarMadagascarMadagascarMadagascarMadaga...
Item Code                                                  299405
Item            Grand TotalVegetal ProductsAnimal ProductsCere...
Element Code                                                74814
Element         Protein supply quantity (g/capita/day)Protein ...
Unit            g/capita/dayg/capita/dayg/capita/dayg/capita/d...
Y2014                                                      177.79
Y2015                                                      173.05
Y2016                                                       173.4
Y2017                                                      175.75
Y2018                                                      176.64
dtype: object

In [7]:
#Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the highest sum in 2017?
df.groupby(['Area'])['Y2017'].sum().sort_values(ascending=False)

Area
Nigeria                        1483268.23
Egypt                           866379.92
South Africa                    517590.54
Ethiopia                        448683.76
Morocco                         388495.36
Ghana                           337599.06
Algeria                         325644.27
United Republic of Tanzania     322616.85
Kenya                           264660.66
Sudan                           239931.92
Cameroon                        232030.43
Angola                          229159.57
Côte d'Ivoire                   224599.01
Uganda                          213950.38
Malawi                          181098.71
Mozambique                      161407.98
Mauritania                      156665.46
Mali                            149928.33
Madagascar                      131197.73
Niger                           126707.58
Benin                           124771.22
Tunisia                         124167.20
Zambia                          103223.77
Burkina Faso                    101855.07
Guinea                           98138.87
Senegal                          95681.15
Zimbabwe                         75919.34
Rwanda                           73663.69
Chad                             71594.68
Sierra Leone                     55311.33
Eswatini                         54343.33
Mauritius                        51114.83
Togo                             49841.88
Congo                            41181.68
Central African Republic         29937.00
Namibia                          29874.89
Liberia                          29342.20
Gabon                            27979.64
Gambia                           23154.18
Djibouti                         22729.91
Botswana                         22101.30
Lesotho                          21267.96
Guinea-Bissau                    19102.77
Cabo Verde                       14650.74
Sao Tome and Principe            12662.63
Seychelles                         442.34
Comoros                             59.84
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Name: Y2017, dtype: float64

In [11]:
#Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the 7th lowest sum in 2017?
df.groupby(['Area'])['Y2017'].sum().sort_values()

Area
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Comoros                             59.84
Seychelles                         442.34
Sao Tome and Principe            12662.63
Cabo Verde                       14650.74
Guinea-Bissau                    19102.77
Lesotho                          21267.96
Botswana                         22101.30
Djibouti                         22729.91
Gambia                           23154.18
Gabon                            27979.64
Liberia                          29342.20
Namibia                          29874.89
Central African Republic         29937.00
Congo                            41181.68
Togo                             49841.88
Mauritius                        51114.83
Eswatini                         54343.33
Sierra Leone                     55311.33
Chad                             71594.68
Rwanda                           73663.69
Zimbabwe                         75919.34
Senegal                          95681.15
Guinea                           98138.87
Burkina Faso                    101855.07
Zambia                          103223.77
Tunisia                         124167.20
Benin                           124771.22
Niger                           126707.58
Madagascar                      131197.73
Mali                            149928.33
Mauritania                      156665.46
Mozambique                      161407.98
Malawi                          181098.71
Uganda                          213950.38
Côte d'Ivoire                   224599.01
Angola                          229159.57
Cameroon                        232030.43
Sudan                           239931.92
Kenya                           264660.66
United Republic of Tanzania     322616.85
Algeria                         325644.27
Ghana                           337599.06
Morocco                         388495.36
Ethiopia                        448683.76
South Africa                    517590.54
Egypt                           866379.92
Nigeria                        1483268.23
Name: Y2017, dtype: float64

In [21]:
#What is the total number of unique countries in the dataset?
df['Area'].nunique()

49

In [22]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [24]:
#Perform a groupby operation on ‘Element’.  What is the total number of the sum of Processing in 2017?
df.groupby(['Element'])[['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']].sum()

,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),10225.56,10235.74,10102.77,10253.84,10258.69
Feed,216927.89,225050.22,228958.65,223705.68,233489.68
Food,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),78718.13,66254.41,69563.68,91645.97,91300.97
Processing,282923.00,287929.00,280631.00,292836.00,308429.00
Production,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,416.00,349.00,89.00,91.00,90.00

In [25]:
#what is the total sum of Wine produced in 2015 and 2018 respectively?
df.groupby(['Item'])[['Y2015','Y2018']].sum()

                         Y2015      Y2018
Item
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]

In [26]:
#What is the mean and standard deviation across the whole dataset for the year 2017 to 2 decimal places?
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000